### PR TITLE
Root: add Plausible

### LINKED ISSUE #76: Add Plausible
We have it set up in the dashboard but need to add the tag to the site, I guess. `stats.elementary.io`.

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes #76

### CODE REVIEW

**Comment by btkostner** [comment]
So, right now there seems to be a bit of a JS bug where the checkout doesn't get sent by js and gets added to the url. So I think that's a blocker for this because we don't want to track people's address in plausible

**Comment by cassidyjames** [comment]
@btkostner where is this happening? I'm seeing a link with a hash in it, but as that's not on our domain, I don't think it would be picked up by Plausible. Unless I'm missing something.

**Comment by btkostner** [comment]
It happens with a JS error during the checkout process. Specifically when JS is not running and you click the shipping rates button.

**Comment by cassidyjames** [comment]
@btkostner if we're requiring JS anyway, can we only enable that button when JS is running? Otherwise I'm not sure how we'd get into that state.

**Comment by btkostner** [comment]
@cassidyjames That was my first reaction, but looking into it seemed extremely hackey and too much work for the alternative, which is just making the form a POST method that would error out.

**Pull request closed without merging**
